brats_preprocessed_destination_folder_train_2020 = "/cs/home/hfyjc3/brats-pretraining_jiachenn/brats_data_preprocessed/Brats20TrainingData"
brats_folder_with_downloaded_data_training_2020 = "/cs/home/hfyjc3/brats_downloaded_data/MICCAI_BraTS2020_TrainingData"

brats_preprocessed_destination_folder_test_2020 = "/cs/home/hfyjc3/brats-pretraining_jiachenn/brats_data_preprocessed/Brats20ValidationData"
brats_folder_with_downloaded_data_test_2020 = "/cs/home/hfyjc3/brats_downloaded_data/MICCAI_BraTS2020_ValidationData"

num_threads_for_brats_example = 8
